[General]
	#Allow drops from fake players
	whitelist = false
	#Insert into players inventory when possible instead of spewing all the items on the ground
	inventoryInsert = false
	#Stack size of dropped loot will be a random number between 0 and maxStackSize
	# Default: 4
	# Range: 0 ~ 64
	maxStackSize = 64
	#Number of dropped stacks per bundle will be between minLootAmount and maxLootAmount
	# Default: 1
	# Range: > 0
	minLootAmount = 1
	#Number of dropped stacks per bundle will be between minLootAmount and maxLootAmount
	# Default: 4
	# Range: > 0
	maxLootAmount = 4
	#List of strings that an item name must not contain in order for it to be considered a valid loot item. Item name can be partial and can contain the mod id as well to disallow an entire mods items.
	disallowedItemNames = ["creative", "spawn_egg", "everycomp", "stonezone", "moremekanismprocessing", "mcw", "handcrafted", "refurbished_furniture", "reinforced_construction", "eternal_starlight", "regions_unexplored", "deeperdarker", "blocksyouneed_luna", "pointblank", "dawnoftimebuilder", "stackedblocks", "displaydelight", "relics:researching_table", "smallships", "delight", "homecoming", "hearthandharvest", "urban_decor", "nomansland"]
